name: Json Comparision

'on':
#   - push
  - workflow_dispatch
jobs:
  Compare-Json-Data-Files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Check out repository and Set up Python
        uses: actions/setup-python@v4
        with:
           python-version: '3.10'
      
      - name: Run Python Script
        run: |
          pip install --upgrade pip
          pip install deep-diff
          python src/comp_json_file.py

      - name: Python Pylint Github Actions for Code Analysis
        run: |
            python -m pip install --upgrade pip
            pip install pylint==2.9.6
            
      - name: Analysing the code with pylint
        run: |
           #find . -name'comp_json_file.py' -exec pylint {} \;
           #find . -name '*.py' -exec pylint {} \;
           pylint src/comp_json_file.py
           #pylint . --reports=y --score n
           #pylint --version
                   
      - run: 'echo "This job status is ${{ job.status }}."'
